### ISSUE TITLE
consider using `prosemirror-autocomplete` instead of `prosemirror-suggest`

### ISSUE THREAD

**Issue by benrbray** [benrbray/noteworthy#44]
the existing suggestion popup needs a makeover, so I need to decide between:

1. keep using [`prosemirror-suggest`](https://www.npmjs.com/package/prosemirror-suggest)
2. switch to [`prosemirror-autocomplete`](https://github.com/curvenote/editor/tree/main/packages/prosemirror-autocomplete)
3. build my own solution

**Comment by rowanc1** [comment]
If there is something that needs changing over in [prosemirror-autocomplete](https://github.com/curvenote/editor/tree/main/packages/prosemirror-autocomplete), happy to try and make it happen. It has worked well for us over in Curvenote.

**Comment by benrbray** [comment]
@rowanc1 Thanks very much for the `prosemirror-autocomplete` package, it's great!  I've decided to switch from `prosemirror-suggest` to `prosemirror-autocomplete`, because:

* I find `prosemirror-autocomplete` a bit easier to use, since it handles *just* the autocompletion and gives me freedom to handle the autocomplete events however I want
* `prosemirror-autocomplete` depends only on core `prosemirror` modules, while `prosemirror-suggest` pulls in many extra dependencies like `remirror` and `react` that were giving me compilation issues

I opened a small PR curvenote/editor#185 to add a `cancelOnSpace` option, let me know what you think!

**Comment by rowanc1** [comment]
So awesome! Glad it is working for you!

I will take a look at the PR soon, thanks for the detailed write up.

**Comment by benrbray** [comment]
Merged!  Code for the autocomplete extension can be found [here](https://github.com/benrbray/noteworthy/tree/master/noteworthy-electron/src/extensions/noteworthy-autocomplete).

![noteworthy-autocomplete](https://user-images.githubusercontent.com/221963/236128386-6b93a0bf-8ecc-4f59-adef-1692a3ebc2f5.gif)
